# Generated by Django 5.1.6 on 2025-02-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fisrt_name', models.TextField()),
                ('last_name', models.TextField()),
                ('dob', models.DateField()),
                ('gender', models.TextField()),
                ('contact_no', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('certifications', models.TextField()),
            ],
        ),
    ]
