# Generated by Django 5.1.6 on 2025-03-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cadidates'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDetails',
            fields=[
                ('TEST_ID', models.AutoField(primary_key=True, serialize=False)),
                ('TEST_NAME', models.CharField(max_length=255, unique=True)),
                ('TEST_DESCRIPTION', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Cadidates',
            new_name='Candidates',
        ),
    ]
