# Generated by Django 5.1.6 on 2025-03-03 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_testdetails_rename_cadidates_candidates'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestEvaluation',
            fields=[
                ('TEST_EVALUATION_ID', models.AutoField(primary_key=True, serialize=False)),
                ('TEST_EVALUATION', models.TextField()),
                ('CANDIDATE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidates')),
                ('TEST_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.testdetails')),
            ],
        ),
    ]
