# Generated by Django 5.1.6 on 2025-03-03 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_testevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentsTable',
            fields=[
                ('APPOINTMENT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('TIME_SLOT', models.DateTimeField()),
                ('CANDIDATE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidates')),
                ('PSYCHOLOGIST_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.psychologist')),
                ('TEST_EVALUATION_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.testevaluation')),
                ('TEST_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.testdetails')),
            ],
        ),
    ]
