# Generated by Django 5.1.6 on 2025-03-04 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_appointmentstable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidates',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
